name: play_shift
description: Play Shift is an modern and efficient iptv player for Windows, MacOs, iOS
publish_to: 'none'
version: 5.0.0+1

environment:
  sdk: ">=3.0.0 <=4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.3
  fluent_ui: ^4.9.2
  isar:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  media_kit: ^1.1.11                             # Primary package.
  media_kit_video: ^1.2.5                        # For video rendering.
  media_kit_libs_video: ^1.0.5 
  m3u_parser_nullsafe: ^1.0.3
  riverpod_annotation: ^3.0.0-dev.3
  path_provider: ^2.1.5
  platform_builder: ^3.0.0
  formz: ^0.8.0
  http: ^1.2.2
  intl: ^0.19.0
  fast_cached_network_image: ^1.2.9
  flutter_launcher_icons: ^0.14.1
  xtream_code_client: ^1.3.4
  auto_route: ^9.2.2

dev_dependencies:
  build_runner: ^2.0.0
  custom_lint:
  flutter_test:
    sdk: flutter
  isar_generator:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  riverpod_lint: ^3.0.0-dev.4
  riverpod_generator: ^3.0.0-dev.11
  auto_route_generator: ^9.0.0
  flutter_lints: ^5.0.0
  msix: ^3.16.8
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/no_image_available.png

msix_config:
  display_name: Play Shift
  publisher_display_name: Marcel Pochert
  identity_name: play_shift
  msix_version: 1.0.0.2
  logo_path: C:\Users\Lukas\DEV\play_shift\assets\logo\play-shift-01.png
  capabilities: internetClient
  publisher: CN=Bonny, O=Bonny, C=DE
  sign_msix: false
